% Script generated by Brainstorm v3.1 (21-Aug-2013)
addpath '/neurospin/meg/meg_tmp/Calculation_Pedro_2014/scripts/' % local processing scripts
load('eventsName.mat') % 

% Input files
folder = '/neurospin/meg/meg_tmp/Calculation_Pedro_2014/brainstorm_db/calc/data';
SubjName='s01';

sFilesOrig = {...
    [folder '/' SubjName '/@raw' 'vsa1_sss_bandpass/data_0raw_' 'vsa1_sss_bandpass.mat'], ...
    [folder '/' SubjName '/@raw' 'vsa2_sss_bandpass/data_0raw_' 'vsa2_sss_bandpass.mat'], ...
    [folder '/' SubjName '/@raw' 'vsa3_sss_bandpass/data_0raw_' 'vsa3_sss_bandpass.mat'], ...
    [folder '/' SubjName '/@raw' 'vsa4_sss_bandpass/data_0raw_' 'vsa4_sss_bandpass.mat']};

SubjNames = {...
    SubjName};

condition_labels= [eventsName 'left click', 'rigth click']  ;

% epoch conditions
for cond=1:2%length(condition_labels)
  
    if cond == 1       % epoching time of the response
        epochWindow = [-0.20, 0.60];
        eventname='1';
        baselineCorrect = [-0.20, -0.0008333333333];
    elseif cond == 2
        epochWindow = [-0.20, 0.60];
        eventname='2';
        baselineCorrect = [-0.20, -0.0008333333333];
     else
        epochWindow = [-0.20, 0.60];
        eventname=condition_labels{cond};
        baselineCorrect = [-0.20, -0.0008333333333];
    end
    
    condition=num2str(cond);
    
    sFiles=sFilesOrig;
    
    % Start a new report
    bst_report('Start', sFiles);
    
    % Process: Import MEG/EEG: Events
    sFiles = bst_process(...
        'CallProcess', 'process_import_data_event', ...
        sFiles, [], ...
        'subjectname', SubjNames{1}, ...
        'condition', condition, ...
        'eventname', eventname, ...
        'timewindow', [], ...
        'epochtime', epochWindow, ...
        'createcond', 0, ...
        'ignoreshort', 1, ...
        'usectfcomp', 0, ...
        'usessp', 1, ...
        'freq', [], ...
        'baseline', baselineCorrect); % not use baseline and instead use high_pass filter
%       'baseline', [-0.20, -0.0008333333333]); % not use baseline and instead use high_pass filter
%       

    % Subject average by conditions
    sFiles = bst_process('CallProcess', 'process_average', ...
        sFiles, [], ...
        'avgtype', 3, ...
        'avg_func', 1, ...  % Arithmetic average: mean(x)
        'keepevents', 0);
      
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);  
end;

