% Script generated by Brainstorm (29-Sep-2015)

% Input files
sFiles = {...
    'link|S01/@default_study/results_wMNE_MEG_GRAD_MEG_MAG_KERNEL_150605_1303.mat|S01/click1_short/data_1024_average_150610_1658_resample.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Z-score normalization: [-200ms,-4ms]
sFiles = bst_process('CallProcess', 'process_zscore_dynamic', sFiles, [], ...
    'baseline', [-0.2, -0.004], ...
    'source_abs', 1, ...
    'dynamic', 1);

% Process: Spatial smoothing (10a)
sFiles = bst_process('CallProcess', 'process_ssmooth', sFiles, [], ...
    'fwhm', 10, ...
    'method', 3, ...  % Average: (euclidian distance + path length) / 2
    'overwrite', 1, ...
    'source_abs', 0);

% Process: Project on default anatomy
sFiles = bst_process('CallProcess', 'process_project_sources', sFiles, []);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

